# src/subsystems/tools/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "tools",
    srcs = [
        "level_editor.cc",
    ],
    hdrs = [
        "level_editor.h",
    ],
    deps = [
        "//src/core",
        "//src/subsystems/renderer",
    ],
)
