# src/resources/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "resources",
    srcs = [
        "asset_loader.cc",
        "resource_manager.cc",
    ],
    hdrs = [
        "asset_loader.h",
        "resource_manager.h",
    ],
    deps = [
        "//src/core",
    ],
)
