# src/engine/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "engine",
    srcs = ["engine.cc"],
    hdrs = ["engine.h"],
    deps = [
        "//src/core",
        "//src/ecs",
        "//src/math",
        "//src/platform",
        "//src/subsystems/input",
        "//src/subsystems/renderer",
    ],
)
