# src/ecs/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ecs",
    srcs = [
        "entity.cc",
        "system.cc",
        "world.cc",
    ],
    hdrs = [
        "component.h",
        "entity.h",
        "system.h",
        "world.h",
    ],
    deps = [
        "//src/core",
    ],
)
