# src/core/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "core",
    srcs = [
        "logging.cc",
        "memory.cc",
        "profiling.cc",
        "time.cc",
    ],
    hdrs = [
        "logging.h",
        "memory.h",
        "profiling.h",
        "time.h",
    ],
    deps = [],
)
