# src/math/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "math",
    srcs = [
        "matrix4.cc",
        "quaternion.cc",
        "vector2.cc",
        "vector3.cc",
    ],
    hdrs = [
        "matrix4.h",
        "quaternion.h",
        "vector2.h",
        "vector3.h",
    ],
    deps = [],
)
