# src/subsystems/input/BUILD
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "input",
    srcs = [
        "input.cc",
    ],
    hdrs = [
        "input.h",
    ],
    deps = [
        "//src/core",
        "@homebrew_sdl2//:sdl2",
    ],
)
